[build]
  functions = "functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
